# Generated by Django 3.0.6 on 2020-05-30 18:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fullname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('mobile', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('pin', models.CharField(max_length=50, null=True)),
                ('national_id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=300)),
                ('status', models.CharField(default='active', max_length=20)),
                ('user_type', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
